export const FETCH_NEWS = 'FETCH_NEWS';
export const GET_NEWS_ARTICLES = 'GET_NEWS_ARTICLES';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
